
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Mar 10 21:46:42 CET 2026
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACKET = 9;
  public static final int CHAR = 39;
  public static final int CONST = 5;
  public static final int GRT = 31;
  public static final int GRTEQ = 32;
  public static final int NOTEQUAL = 30;
  public static final int LPAREN = 12;
  public static final int SEMI = 6;
  public static final int LSEQ = 34;
  public static final int MINUS = 17;
  public static final int RPAREN = 13;
  public static final int LS = 33;
  public static final int BOOL = 38;
  public static final int QMARK = 28;
  public static final int COMMA = 8;
  public static final int INC = 15;
  public static final int DIV = 21;
  public static final int PLUS = 19;
  public static final int ASSIGN = 7;
  public static final int DOT = 23;
  public static final int EOF = 0;
  public static final int RETURN = 35;
  public static final int RBRACKET = 10;
  public static final int EQUAL = 29;
  public static final int NEW = 18;
  public static final int error = 1;
  public static final int MUL = 20;
  public static final int NUMBER = 37;
  public static final int MOD = 22;
  public static final int IDENT = 36;
  public static final int VOID = 11;
  public static final int COL = 14;
  public static final int LBRACE = 3;
  public static final int ENUM = 26;
  public static final int READ = 24;
  public static final int RBRACE = 4;
  public static final int PROG = 2;
  public static final int DEC = 16;
  public static final int PRINT = 25;
  public static final int LENGTH = 27;
}

